<%
var buildDate = new Date().toGMTString()
var bannerMessage = '- THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY -';
var bannerBuild = '- Generated by Gulp.\n// - @build: ' + buildDate;

%>//-----------------------------------
<%= '//\n//\n//\n//\n//\n// ' + bannerMessage +'\n//' %>
<%= '// ' + bannerBuild + '\n//\n//\n//\n//\n//' %>
//-----------------------------------

'use strict';
use(function () {

  var data = {};

  data.icons = [
  <%
    // Sort Icons alphabetically
    var glyphsSorted = _.sortBy(glyphs, function(obj) { return obj.name });

  _.each(glyphsSorted, function(glyph) {
    %>"<%= className %>-<%= glyph.name %>",
  <% }); %>
  ];

  return data;

});
