/**
 *
 *
 *
 * - THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY -
 * - Generated by Gulp (gulp-babel).
 *
 *
 *
 *
 */


//-----------------------------------
// Eaton: Global Methods
//-----------------------------------
'use strict';

var App = App || {};
App.global = function () {

  // // Accepts and strings/integers and logs them to console
  // const globalExample = function(value) {
  //   console.log(value);
  // };
  //
  // return {
  //   globalExample
  // };

}();