/**
 *
 *
 *
 * - THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY -
 * - Generated by Gulp (gulp-babel).
 *
 *
 *
 *
 */


//-----------------------------------
// Eaton: Global Methods
//-----------------------------------
'use strict';

var App = App || {};
App.global = function () {

  // const globalExample = (value) => { };

  // return {
  //   globalExample
  // };

}();