/**
 *
 *
 *
 * - THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY -
 * - Generated by Gulp (gulp-babel).
 *
 *
 *
 *
 */


//-----------------------------------
// Compnent: TTIL
//-----------------------------------
'use strict';

var App = window.App || {};
App.ttilList = function () {

  var $componentEl = $('.carousel-component-slide');

  var init = function init() {
    initCarousels();
  };

  /**
   * Initialize Bootstrap Carousel
   */
  var initCarousels = function initCarousels() {
    $componentEl.slick({
      slidesToShow: 1,
      slidesToScroll: 1,
      autoplay: true,
      autoplaySpeed: 5000,
      dots: true,
      dotsClass: 'carousel-component__dots',
      prevArrow: $('.carousel-component__arrow--prev'),
      nextArrow: $('.carousel-component__arrow--next')

    });
  };

  /**
   * If containing DOM element is found, Initialize and Expose public methods
   */
  if ($componentEl.length > 0) {
    init();
  }
}();