/**
 *
 *
 *
 *
 *
 * - THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY - 
 *
 * - Generated by Gulp (gulp-babel).
 *
 *
 *
 *
 *
 */


//-----------------------------------
// Component : Search
//-----------------------------------
'use strict';

var App = window.App || {};

App.search = function () {

  // Variable Declarations
  var componentClass = '.eaton-footer-back-to-top';
  var $componentElement = $(componentClass);
  var isAEMAuthorMode = App.global.utils.isAEMAuthorMode();
  var lastScrollTop = 0;

  /**
  * Init
  */
  var init = function init() {
    // If not in AEM Author Mode & component exists on page - initialize scripts
    if (!isAEMAuthorMode) {
      // console.log('Initialize Search');
      addEventListeners();
    }
  };

  /**
   * Bind All Event Listeners
   */
  var addEventListeners = function addEventListeners() {
    $(window).on('scroll', function (event) {
      var scrollTop = $(window).scrollTop();
      var isGoingDown = lastScrollTop < scrollTop;
      $componentElement.toggleClass('visible', isGoingDown);
      lastScrollTop = scrollTop;
    });
  };

  /**
  * If containing DOM element is found, Initialize and Expose public methods
  */
  if ($componentElement.length > 0) {
    init();
  }
}();